const titulos = [
    "Metodologias Ágeis Extreme Programming e Scrum para o Desenvolvimento de Software",
    "METODOLOGIAS ÁGEIS PARA O DESENVOLVIMENTO DE SOFTWARES",
    "Comparação entre Metodologias Ágeis e Tradicionais para o Desenvolvimento de Software",
    "METODOLOGIAS ÁGEIS PARA O DESENVOLVIMENTO DE SOFTWARE: APLICAÇÃO E O USO DA METODOLOGIA SCRUM EM CONTRASTE AO MODELO TRADICIONAL DE GERENCIAMENTO DE PROJETOS",
    "A Implantação das metodologias ágeis de desenvolvimento de software scrum e extreme programming(XP) uma alternativa para pequenas empresas do setor de tecnologia da informação",
    "Favorabilidade na adoção de práticas de metodologias ágeis no desenvolvimento de software",
    "A IMPORTÂNCIA DO DESIGN CENTRADO NO USUÁRIO EM METODOLOGIAS AGEIS COMO REQUISITO DE USABILIDADE",
    "Modelo de Desenvolvimento de Objetos de Aprendiagem Baseado em Metodologias Ágeis e Scaffoldings",
    "Uma análise sobre o uso de metodologias ágeis de desenvolvimento de software em startups",
    "Aplicação da UML no contexto das metodologias ágeis",
    "REVISÃO INTEGRATIVA SOBRE O USO DE METODOLOGIAS ÁGEIS NO GERENCIAMENTO DE PROJETOS DE INFRAESTRUTURA HOSPITALAR",
    "Taylorização e auto-taylorização do trabalho: as metodologias ágeis na indústria de software",
    "ADOÇÃO DE METODOLOGIAS ÁGEIS EM PEQUENAS EMPRESAS DE SOFTWARE: Desafios Iniciais e Benefícios Organizacionais",
    "ADOÇÃO DE METODOLOGIAS ÁGEIS NA GESTÃO DE TI NO SETOR PÚBLICO: UMA REVISÃO SISTEMÁTICA DA LITERATURA",
    "Revisão Sistemática da Adoção do Scrum no Desenvolvimento de Software",
    "Um estudo sobre metodologias ágeis e sua correlação com o êxito em projetos de software.",
    "Os desafios da gestão de equipes remotas com metodologias ágeis: uma revisão sistemática da literatura sobre aspectos humanos e técnicos",
    "Uma Abordagem para a Implementação da Gerência do Fornecedor usando Metodologias Ágeis",
    "MAPEANDO O CAMINHO PARA A SUSTENTABILIDADE: ANÁLISE SWOT",
    "Título 20SCPA software de gerenciamento de equipes de desenvolvimento utilizando metodologias ágeis"
];