function getFallback () {
    
    return [
        
        ["artigo", "apresenta", "vantagens", "metodologias", "ágeis", "desenvolver", "software", "tradicionais", "particular", "apresentadas", "principais", "características", "práticas", "extreme", "programming", "scrum", "feitas", "comparações", "tradicionais", "procurando", "enfatizar", "baseadas", "pessoas", "processos", "planejamentos", "finalmente", "desvantagens", "apresentados", "resultados", "empíricos"],

        ["desenvolvimento", "software", "atividade", "complexa", "devido", "complexidade", "engenharia", "criada", "objetivo", "aumentar", "produtividade", "melhorar", "qualidade", "produto", "gerado", "diversas", "metodologias", "práticas", "surgiram", "intenção", "direcionar", "desenvolvimento", "inicialmente", "vieram", "chamadas", "tradicionais", "cascata", "prototipação", "incremental", "traziam", "junto", "consigo", "muita", "rigidez", "passo", "delas", "gerava", "diversos", "artefatos", "documentações", "mesmo", "resultados", "entregues", "projetos", "geravam", "abaixo", "esperado", "isso", "ágeis", "proposta", "fornecer", "agilidade", "resposta", "flexibilidade", "adaptação", "trazendo", "diferencial", "competitivo", "velocidade", "resultados", "revisão", "técnica", "apresentar", "mecanismo", "ágil", "modo", "atender", "rapidez", "qualidade", "reduzindo", "consumo", "desnecessário", "recursos", "auxiliando", "promoção", "sustentável", "compreendeu-se", "técnicas", "trouxeram", "evolução", "troca", "experiência", "comunicação", "transmissão", "conhecimento", "confiança", "pessoas", "cliente", "equipe", "cresça", "satisfação", "cliente", "seja", "maior"],
        
        ["artigo", "comparação", "metodologias", "tradicionais", "desenvolvimento", "software", "ágeis", "particular", "feita", "extreme", "programming", "xp", "metodologia", "ágil", "usada", "modelo", "clássico", "sequencial", "práticas", "apresentadas", "enfatizando", "características", "ideais", "projetos", "devem", "rápido", "requisitos", "alterados", "constantemente", "clientes"],
        
        ["artigo", "fomentado", "estudos", "bibliográficos", "metodologias", "ágil", "tradicional", "objetivo", "apresentar", "principais", "problemas", "encontrados", "século", "xxi", "respeito", "desenvolvimento", "projetos", "software", "disponíveis", "serão", "apresentadas", "formas", "tradicional", "ferramenta", "scrum", "valores", "práticas", "apresentados", "modo", "identificar", "justificar", "diferenças", "demonstrar", "quadro", "comparativo", "tradicional", "quais", "comparados", "analisados", "processos", "ágeis", "tradicionais", "intuito", "proporcionar", "condições", "favoráveis", "avaliação", "escolha", "metodologia", "atenda", "necessidades", "clientes", "software"],
        
        ["apresenta", "caso", "implantação", "metodologias", "ágeis", "desenvolvimento", "scrum", "extreme", "programming", "xp", "ressalta", "abordagem", "alternativa", "pequenas", "empresas", "tecnologia", "informação", "ti", "necessária", "função", "processos", "formais", "desenvolvimento", "perfil", "acarreta", "certos", "problemas", "construção", "softwares", "objetivo", "viabilizar", "solução", "modelo", "referidas", "metodologias", "propósito", "será", "conseguido", "mediante", "levantamento", "conceitos", "volta", "tema", "apresentação", "implantar", "final", "estudo", "evidencia", "contribuir", "organização", "formalização", "processo", "software", "utilizado", "favorecê-las", "ganho", "produtividade"],
        
        ["objetivo", "principal", "estudo", "desenvolvimento", "modelo", "avaliação", "grau", "favorabilidade", "adoção", "práticas", "metodologias", "ágeis", "organizações", "predomina", "tradicionais", "softwares", "alcançar", "revisados", "conceitos", "teóricos", "relacionados", "ágeis", "destacando", "confronto", "tradicionais", "revisão", "elaborou-se", "instrumento", "pesquisa", "submetido", "estratégia", "survey", "junto", "especialistas", "software", "banco", "varejo", "brasileiro", "reconhecido", "expressividade", "volume", "ativos", "operações", "também", "abrangência", "transnacional", "atuação", "dados", "quantitativos", "oriundos", "questões", "fechadas", "analisados", "técnicas", "estatísticas", "primeira", "técnica", "multivariada", "análise", "fatorial", "exploratória", "aplicada", "validação", "estrutura", "perspectivas", "relacionadas", "proposto", "segunda", "univariada", "frequência", "respostas", "conforme", "distribuição", "mesmas", "qualitativos", "aberta", "conteúdo", "qualitativa", "temática", "evidenciadas", "frequências", "oriundas", "quantitativa", "resultados", "destacam-se", "contexto", "proposto", "estatística", "organização", "estudo", "limitação", "reside", "fato", "sido", "desenvolvido", "base", "única", "bancária", "permitindo", "generalização", "externa", "propicie", "teórica", "presente", "modelo", "poderá", "aplicado", "predomínio", "software"],
        
        ["virtude", "competividade", "mercado", "desenvolvimento", "software", "longo", "últimas", "décadas", "métodos", "software", "geração", "especializando", "tornando", "processos", "eficientes", "entretanto", "metodologia", "foca", "explicitamente", "design", "centrado", "usuário", "implica", "insatisfação", "cliente", "adequação", "necessidades", "retrabalho", "deficiência", "requisitos", "atendam", "projeto", "problemas", "acabam", "afetando", "custos", "cronograma", "equipes", "desenvolvimento", "decorrência", "vulnerabilidades", "presente", "artigo", "finalidade", "correlacionar", "modelos", "ágeis", "técnicas", "usabilidade", "usuário", "gerar", "satisfação", "clientes", "revisão", "bibliográfica", "sistemática", "abordada", "propõe-se", "abordar", "artigos", "teses", "acadêmicas", "referentes", "metodologias", "usabilidade", "fazendo", "convergência", "benefícios", "metodologias", "correlação", "elas", "resultados", "encontradas", "comunicação", "usuários", "partes", "interessadas", "sanadas", "utilização", "eficiente", "análise", "aliado", "ferramentas", "direcionadas", "usuário"],

        ["desenvolvimento", "objetos", "aprendizagem", "exige", "modelos", "instrucionais", "esenvolvimento", "flexíveis", "tratar", "categoria", "software", "conjunto", "requisitos", "específicos", "demandas", "tecnológicas", "singulares", "metodologias", "ágeis", "facilitar", "processo", "permitindo", "modelagem", "funcionalidades", "baseados", "comportamento", "aluno", "presente", "artigo", "objetivo", "discorrer", "experiência", "aprendizagem", "baseado", "interface", "baseada", "scaffoldings"],

        ["metodologias", "ágeis", "utilizadas", "tipos", "empresas", "desenvolvimento", "software", "incluindo", "startups", "startups", "seguem", "processos", "rigorosa", "maneira", "completa", "forma", "necessário", "analisar", "definem", "executam", "práticas", "descritas", "ágeis", "conclusão", "curso", "visa", "membros", "utilizam", "prática", "isso", "realizou-se", "pesquisa", "opinião", "survey", "obteve", "respostas", "válidas", "avaliadas", "pessoas", "atuam", "atuaram", "ramo", "startups", "junto", "realização", "entrevistas", "meio", "resultados", "ambos", "analisados", "relacionados", "mostram", "recomendações", "rigorosa", "conjunto", "possuem", "condições", "favoráveis", "influenciam", "seguir", "não", "identificou-se", "organizações", "preocupam", "etapa", "documentação", "realizam", "garantia", "qualidade", "produto", "conversas", "clientes", "feedbacks", "fornecidos", "mesmos"],

        ["modelo", "documentação", "estudado", "cursos", "superiores", "computação", "metodologias", "ágeis", "ocupam", "mercado", "atual", "manifesto", "pregam", "simplicidade", "rapidez", "características", "processos", "minuciosos", "documentação", "apresenta", "resultados", "obtidos", "aplicar", "questionário", "várias", "empresas", "desenvolvimento", "software", "estado", "minas", "gerias", "intenção", "descobrir", "aplicação", "contexto", "software", "estatísticos", "apontam", "necessidade", "revisão", "paradigmas", "engenharia"],

        ["crescente", "demanda", "infraestrutura", "hospitalar", "qualidade", "aliada", "desafios", "prazos", "reduzidos", "restrições", "orçamentárias", "situações", "emergenciais", "impulsiona", "busca", "métodos", "eficazes", "gerenciamento", "projetos", "setor", "saúde", "contexto", "metodologias", "ágeis", "originadas", "desenvolvimento", "software", "fundamentadas", "manifesto", "ágil", "destacando", "capacidade", "promover", "entregas", "incrementais", "flexibilidade", "comunicação", "contínua", "equipes", "multidisciplinares", "práticas", "scrum", "kanban", "lean", "mostram", "adequadas", "atender", "constantes", "mudanças", "requisitos", "necessidades", "específicas", "ambientes", "hospitalares", "oferecendo", "respostas", "rápidas", "eficientes", "frente", "imprevistos", "observados", "durante", "pandemia", "covid-19", "presente", "estudo", "analisou", "revisão", "integrativa", "aplicação", "hospitalares", "resultado", "demonstrou", "adoção", "otimizar", "execução", "obras", "reduzir", "custos", "agilizar", "garantir", "qualidade", "entregas", "evidenciando", "ágeis", "promovem", "eficiência", "conclui-se", "abordagens", "representam", "alternativa", "inovadora", "estratégica", "modernização", "gestão", "saúde", "pública"],

        ["proposta", "artigo", "analisar", "criticamente", "metodologias", "ágeis", "presentes", "produção", "software", "objetivo", "questionamos", "medida", "formas", "organização", "reproduzem", "antigas", "trabalho", "sobretudo", "taylor-fordistas", "toyotistas", "contrariamente", "teses", "apresentam", "emergência", "imaterial", "paradigmático", "ruptura", "industrial", "objetivo", "debater", "novo", "presente", "século", "xxi", "configurariam", "adaptações", "taylor-fordismo", "toyotismo", "fronteira", "produtiva", "explorada", "capital", "séculos", "imaterial"],

        ["implementação", "metodologias", "ágeis", "sido", "diferencial", "empresas", "adotam", "trata-se", "reduzem", "custos", "empresa", "melhoram", "comunicação", "equipes", "desenvolvimento", "gestão", "aceleram", "resultados", "entregas", "produtos", "promovem", "benefícios", "aumento", "produtividade", "equipes", "transparência", "processos", "redução", "retrabalho", "contínuas", "valor", "cliente", "fortalecerem", "colaboração", "capacidade", "adaptação", "mudanças", "entanto", "pequenas", "enfrentar", "desafios", "tentar", "implementá-las", "pois", "possuem", "limitações", "recursos", "escassos", "dificuldade", "treinamento", "capacitação", "equipes", "artigo", "objetivo", "analisar", "vantagens", "quais", "dificuldades", "enfrentadas", "software", "implementando-as", "fases", "iniciais", "implementadas", "sucesso", "metodologia", "adotada", "realização", "pesquisa", "bibliográfica", "material", "estudado", "observou-se", "representam", "ferramentas", "altamente", "eficazes", "promover", "flexibilidade", "inovação", "processos", "organizacionais", "conclui-se", "que", "corretamente", "seguidas", "conforme", "princípios", "manifesto", "ágil", "citado", "artigo", "possibilitam", "organizações", "destacarem", "âmbito", "competitivo"],

        ["revisão", "sistemática", "literatura", "rsl", "objetivo", "identificar", "recuperar", "analisar", "práticas", "descritas", "produção", "científica", "relacionadas", "gestão", "desenvolvimento", "ágil", "tecnologias", "inovações", "produtos", "tecnologia", "informação", "ti", "panorama", "construído", "busca", "subsidiar", "gestores", "públicos", "tomada", "decisão", "direcionamento", "estratégico", "setor", "utilização", "metodologias", "ágeis", "motivação", "estudo", "centrada", "desafios", "enfrentados", "setores", "capacidade", "manter", "inovar", "otimizar", "processos", "internos", "cenário", "complexidade", "gerencial", "resulta", "comprometimento", "qualidade", "melhor", "alocação", "recursos", "especial", "equipe", "tais", "particularmente", "críticos", "adoção", "ágeis", "considerada", "fator", "favorece", "realização", "entregas", "tempo", "geração", "valor", "longo", "processo", "disso", "proporciona", "adaptação", "requisitos", "constante", "mudança", "promove", "sistemas", "entregues", "principalmente", "aspectos", "facilidade", "testes", "rapidez", "correção", "falhas", "contextualiza", "critérios", "utilizados", "aplicação", "sendo", "fatores", "essenciais", "sustentar", "execução", "eficaz", "observa", "ferramentas"],

        ["desenvolvimento", "software", "evoluído", "significativamente", "últimas", "décadas", "impulsionado", "necessidade", "entregas", "rápidas", "flexíveis", "centradas", "cliente", "contexto", "metodologias", "ágeis", "emergem", "alternativas", "modelos", "tradicionais", "desenvolvimento", "oferecendo", "abordagens", "interativas", "colaborativas", "artigo", "objetivo", "analisar", "revisão", "literatura", "metodologia", "ágil", "scrum", "alternativa", "eficiente", "software", "isso", "selecionadas", "obras", "referência", "biblioteca", "virtual", "utilizando", "termos", "engenharia", "software", "metodologias", "software", "scrum", "fundamentação", "teórica", "contempla", "evolução", "engenharia", "software", "princípios", "manifesto", "detalhamento", "papéis", "artefatos", "cerimônias", "framework", "scrum", "resultados", "apontam", "contribui", "organização", "equipes", "entrega", "contínua", "valor", "melhor", "gestão", "projetos", "ambientes", "dinâmicos", "conclui-se", "adoção", "depende", "compreensão", "fundamentos", "preparo", "equipes", "mudanças", "culturais", "estruturais", "que", "implementado", "proporciona", "controle", "prazos", "qualidade", "alinhamento", "objetivos", "cliente", "sendo", "viável", "adotada"],

        ["artigo", "investiga", "eficácia", "metodologias", "ágeis", "projetos", "desenvolvimento", "software", "sucesso", "estudo", "aprofunda", "compreensão", "práticas", "princípios", "fundamentais", "ágeis", "manifesto", "ágil", "ágeis", "disso", "pesquisa", "analisa", "diversos", "fatores", "executivo", "maturidade", "emocional", "equipes", "envolvimento", "usuários", "otimização", "recursos", "qualificação", "membros", "equipe", "elementos", "impactam", "taxa", "sucesso", "investigados", "obstáculos", "desafios", "comuns", "organizações", "enfrentam", "implementar", "metodologias", "incluindo", "resistência", "mudança", "conflitos", "culturais", "enfatiza", "relevância", "melhoria", "desempenho", "fornece", "diretrizes", "valiosas", "buscam", "adotar", "aprimorar", "oferece", "visão", "abrangente", "universo", "ágil", "abordando", "vantagens", "desafios", "apresenta", "recomendações", "implementação", "abordagens", "empresas", "software"],
        
        ["estudo", "analisou", "desafios", "estratégias", "relacionadas", "gestão", "equipes", "ágeis", "contextos", "remotos", "híbridos", "engenharia", "software", "considerando", "dimensões", "humanas", "gerenciais", "técnicas", "pesquisa", "propósito", "identificar", "categorizar", "principais", "dificuldades", "enfrentadas", "distribuídas", "avaliar", "propostas", "literatura", "recente", "compreender", "impacto", "gerado", "cultura", "digital", "automação", "inteligência", "artificial", "ia", "prática", "agilidade", "contemporânea", "metodologia", "utilizada", "baseou-se", "revisão", "sistemática", "rsl", "conduzida", "protocolo", "prisma", "adaptado", "busca", "bases", "scopus", "scielo", "science", "abrangendo", "período", "2015", "2025", "selecionados", "trinta", "estudos", "atenderam", "critérios", "inclusão", "contemplando", "aspectos", "humanos", "comunicação", "liderança", "engajamento", "técnicos", "qualidade", "devops", "integração", "entrega", "contínuas", "ci/cd", "resultados", "evidenciaram", "que", "dimensão", "humana", "associados", "perda", "interações", "presenciais", "dificuldade", "manutenção", "coesão", "aumento", "risco", "esgotamento", "emocional", "burnout", "técnica", "destacam-se", "falhas", "pipelines", "conjuntos", "processos", "automatizados", "ci/cd", "morosidade", "revisões", "assíncronas", "código", "maturidade", "processos", "eficientes", "identificadas", "envolvem", "implementação", "confiança", "redefinição", "papel", "ênfase", "autonomia", "empatia", "incorporação", "tecnologias", "otimização", "ágil", "conclui-se", "eficácia", "ágil", "ambientes", "distribuídos", "depende", "articulação", "equilibrada", "organizacional", "técnica", "empática"],
        
        ["artigo", "propõe", "abordagem", "práticas", "utilizando", "métodos", "ágeis", "gerenciar", "procedimento", "aquisição", "contexto", "empresas", "desenvolvimento", "software", "baseado", "processo", "supplier", "agreeement", "management", "cmmi-dev", "mrmps-sw"],
        
        ["avanço", "discussões", "sustentabilidade", "transição", "século", "xxi", "tornou-se", "essencial", "compreender", "temas", "impactam", "estratégia", "organizacional", "estudo", "objetivo", "analisar", "aplicação", "matriz", "swot", "campo", "engenharia", "sustentabilidade", "destacando", "papel", "identificação", "oportunidades", "ameaças", "fortes", "fracos", "projetos", "sustentáveis", "isso", "realizou-se", "revisão", "sistemática", "bibliométrica", "publicações", "científicas", "período", "2002", "2022", "abrangendo", "bases", "dados", "science", "scopus", "scielo", "google", "acadêmico", "resultados", "quantitativos", "evidenciam", "crescimento", "significativo", "tema", "especialmente", "2019", "análise", "qualitativa", "demonstrou", "versatilidade", "swot", "frequentemente", "combinada", "metodologias", "consolidar", "fatores", "críticos", "diferentes", "áreas", "pesquisa", "ferramenta", "mostrou-se", "relevante", "estudos", "qualitativos", "quantitativos", "sendo", "amplamente", "utilizada", "embasar", "formulação", "estratégias", "voltadas", "sustentabilidade", "conclui-se", "contribui", "maneira", "significativa", "promoção", "práticas", "sustentáveis", "auxiliando", "empresas", "instituições", "adaptação", "modelos", "econômicos", "produtivos", "ecológicos", "alinhados", "demandas", "contemporâneas"],
        
        ["mundo", "tecnologia", "constante", "mudança", "requisitos", "alterações", "modelo", "negócio", "empresas", "solicitadas", "equipes", "desenvolvimento", "software", "instante", "necessitando", "muita", "interação", "pessoas", "respostas", "rápidas", "mudanças", "propiciou", "crescente", "adoção", "metodologias", "ágeis", "software", "dentre", "destacando-se", "framework", "scrum", "principais", "características", "indivíduos", "interações", "processos", "ferramentas", "funcionando", "extensa", "documentação", "colaboração", "clientes", "negociação", "contratos", "mudanças", "seguir", "plano", "características", "fundamentais", "organizações", "buscam", "excelência", "mercado", "informação", "entretanto", "existem", "softwares", "ágil", "motivou", "ferramenta", "customizada", "utilização", "scrum", "sendo", "denominada", "colaborativo", "projetos", "scpa", "voltada", "otimizar", "tempo", "gerenciamento", "melhorar", "qualidade", "produtos", "desenvolvidos", "scpa", "permite", "controle", "efetivo", "requisitos", "chamados", "histórias", "contexto", "ágeis", "realizar", "devidas", "priorizações", "iteração", "inclui", "facilitadores", "possibilidade", "adicionar", "comentários", "anexar", "arquivos", "cadastrar", "documentar", "testes", "maneira", "individual", "história", "possibilitando", "opção", "geração", "gráfico", "burndown", "indicador", "indispensável", "monitoramento", "produtividade", "poderá", "gerado", "qualquer", "durante", "ciclo", "desenvolvimento"]
    ]
}